# Astoria Default Config File

[mqtt]
host = "::1"
port = 1883
enable_tls = false
force_protocol_version_3_1 = true

topic_prefix = "astoria"

[kit]
name = "Astoria Development"
version = "0.0.0.0dev"

[wifi]
interface = "wlan0"
bridge = "br0"
