name: Build source and binary packages

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install APT dependencies
        run: sudo apt install build-essential devscripts debhelper equivs
      - name: Start Mosquitto MQTT broker
        uses: namoshek/mosquitto-github-action@v0.1.0
      - name: Install Poetry
        run: pip install poetry
      - name: Use in-project virtualenv
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
        working-directory: repo
      - name: Build Debian package
        run: make debian
        working-directory: repo
      - uses: actions/upload-artifact@v2
        with:
          name: debian
          path: |
            *.dev
            *.dsc
            *.changes
            *.tar.*
            *.buildinfo
            *.build